// 本地化资源文件
const messages = {
  en: {
    message: {
        download: 'Download Now',
        web3_description: 'Hello, welcome to the web3express seed user platform, where you can promote your own project or projects that you believe in. with this platform, you can effectively organize various individuals within your industry for promotion. you can also organize crowdfunding activities efficiently, facilitating the healthy development of your projects!',
        happy_user:'I am a Happy Internet User',
        you_may_need:'You may need',
        web3_user_platform:'Web3Express [Seed User Platform] QR Code:',
        experienced_user:'I am an Experienced User',
        community_leader:'I am a Community Leader',
        your_referrer:'Your Referrer: ',
        promotion_bounty:'Promotion Bounty',
        crowdfunding_purpose:'Crowdfunding Purpose',
        no_established_autonomous_organization:'No established autonomous organization for crowdfunding yet',
        initiate:'Initiate',
        rights_obligations:'Rights and Obligations',
        rights:'Rights',
        obligations:'Obligations',
        introduction:'Introduction',
        share_dissemination:'establishment of sharing and dissemination',
        code_dissemination:'code dissemination',
        tags_categories:'tags/categories',
        description:'description:',
        seed_user_rights:'seed user rights',
        seed_user_obligations:'seed user obligations',
        saving_dissemination_materials:'saving dissemination materials',
        collapse:'Collapse',
        expand_more:'Expand more',
        qr_code:'QR Code',
        total_bounty:'Total bounty',
        completed:'Completed',
        details:'Details',
        crowdfunding_reached:'Crowdfunding reached: (currency)',
        me:'me',
        non_management_member:'Non-Management Member',
        management_member:'Management member',
        crowdfunding_amount:'Crowdfunding Amount',
        detailed_rules:'Detailed Rules',
        start_time:'Start Time',
        end_time:'End Time',
        additional_crowdfunding:'Additional Crowdfunding',
        participate_in_crowdfunding:'Participate in Crowdfunding',
        crowdfunding_timeout:'Current crowdfunding has exceeded the time limit without completion',
        proposal_postponement:'Initiate a proposal for postponement',
        execute_crowdfunding_cancellation:'Execute crowdfunding cancellation',
        crowdfunding_deadline:'Current crowdfunding has reached the deadline',
        execute_crowdfunding_allocation:'Execute crowdfunding allocation',
        initiate_share:'Initiate dissemination-oriented sharing',
        modify_sharing_information:'Modify sharing information:',
        account_owner:'Account owner:',
        organization_affiliation:'Organization affiliation:',
        joined:'Joined',
        join:'Join',
        not_joined:'Not joined',
        personal_step:'If the owner is an individual, modifications can be made by the owner.',
        organization_step:'If the owner is an organization, modifications require the agreement of more than 1/2 of the members',
        members:'Members',
        token_dissemination:'Token dissemination',
        switch_to_app:'Switch to app',
        switch_to_website:'Switch to website',
        apk_address:'Please enter the correct apk download address or Ipfs-CID',
        enter_package_name:'Enter the correct package name of the android app',
        submit_modifications:'Submit modifications',
        back:'Back',
        title:'Title',
        submit_modification_proposal:'Submit modification proposal',
        create_dissemination:'Create dissemination-oriented sharing',
        establish_crowdfunding:'Establish crowdfunding autonomous organization:',
        note:'Note: This operation requires an additional payment of "1 coin" to the fixed account of the organization permanently.',
        add_crowdfunding:'Add crowdfunding to autonomous organization:',
        purpose_crowdfunding:'Purpose of this crowdfunding',
        organization_id:'Organization ID (optional):',
        soft_cap:'Soft cap (minimum):',
        hard_cap:'Hard cap (maximum):',
        deadline_block_height:'Deadline block height (time):',
        select_time:'Select time (automatically converted to height)',
        destruction_ratio:'Destruction ratio',
        my_first_investment:'My investment (first transaction)',
        rent_nodes:'Rent nodes:',
        adopt_zero_knowledge:'Adopt zero-knowledge proof',
        convert_current_ownership:'Convert current ownership',
        text_is:'is',
        current_page_id:'Current Page ID',
        create_promotion_crowdfunding:'Create promotion crowdfunding',
        establish_organization_first:'Error! Need to establish an autonomous organization first: ',
        your_account:'Your account:',
        create_promotion_steps:'Create promotion task in three steps:',
        generate_account:'1. Deploy privacy promotion contract to automatically generate an account',
        create_task:'2. Create and fund the task (current interface)',
        vote_start_task:'3. Vote and start the task',
        privacy_contract:'Privacy contract',
        deploy_contract:'Deploy contract to get account',
        privacy_contract:'Privacy contract promotion account',
        privacy_contract_collection_account:'Privacy contract collection account',
        description_task:'Description of this task',
        organization_investment:'Organization\'s investment',
        my_investment:'My investment',
        available:'Available',
        Wallet_plugin_user_selection:'Wallet plugin user selection',
        current_selection:'Current selection',
        hint:'Hint',
        confirm:'Confirm',
        cancel:'Cancel',
        submit:'Submit',
        code_dissemination_required:'Code dissemination is required',
        tags_categories_required:'Tags/categories for dissemination are required',
        explanation_rights_required:'Explanation of seed user rights for dissemination is required',
        explanation_obligations_required:'Explanation of seed user obligations for dissemination is required',
        cannot_signature:'Cannot directly call with personal signature',
        not_owner:'You are not the owner!',
        operation_successful:'Operation successful',
        operation_failed:'Operation failed',
        unknown_error:'Unknown error!',
        dissemination_required:'Dissemination description is required',
        dissemination_subject_required:'Dissemination subject is required',
        asset_id_already_occupied:'Asset ID is already occupied',
        activities_ongoing:'There are ongoing crowdfunding activities',
        deadline_earlier_than_current:'Deadline time (block height) is earlier than the current time',
        insufficient_account_balance:'Insufficient account balance!',
        system_error:'System error',
        cannot_find_root:'Cannot find the \'root\' autonomous organization',
        tt:'',
        tt:'',
        tt:'',
    }
  },
  zh_cn: {
    message: {
        download: '立即下载',
        web3_description:'你好，欢迎来到web3express种子用户平台，对你的项目或你看好的项目发起推广。通过该平台，你可以有效组织所处行业内各类人员进行推广，你可有效组织众筹，形成项目的良性发展',
        happy_user:'我是快乐网友',
        you_may_need:'你可能需要',
        web3_user_platform:'WebExpress【种子用户平台】二维码：',
        experienced_user:'我是资深用户',
        community_leader:'我是社区大佬',
        your_referrer:'你的推荐者：',
        promotion_bounty:'推广赏金',
        crowdfunding_purpose:'众筹目的',
        no_established_autonomous_organization:'还没有众筹成立自治组织',
        initiate:'发起',
        rights_obligations:'权利与义务',
        rights:'权利',
        obligations:'义务',
        introduction:'介绍',
        collapse:'收起',
        expand_more:'展开更多',
        qr_code:'二维码',
        total_bounty:'总赏金',
        completed:'完成',
        details:'详细',
        crowdfunding_reached:'众筹已达：(币)',
        me:'我',
        non_management_member:'非管理成员',
        management_member:'管理成员',
        crowdfunding_amount:'众筹额度',
        detailed_rules:'详细规则',
        start_time:'开始时间',
        end_time:'结束时间',
        additional_crowdfunding:'追加众筹',
        participate_in_crowdfunding:'参与众筹',
        crowdfunding_timeout:'当前众筹未完成已超时',
        proposal_postponement:'发起延期提案',
        execute_crowdfunding_cancellation:'执行众筹撤销',
        crowdfunding_deadline:'当前众筹已达成已截至',
        execute_crowdfunding_allocation:'执行众筹分配',
        initiate_share:'发起传播型分享',
        modify_sharing_information:'修改分享资料: ',
        account_owner:'所属账号: ',
        organization_affiliation:'所属组织: ',
        joined:'已加入',
        join:'加入',
        not_joined:'未加入',
        personal_step:'所有者为个人，由所有者操作即可完成修改。',
        organization_step:'所有者为组织，需要1/2以上人同意才能完成修改',
        token_dissemination:'传播代币',
        switch_to_app:'切换为App',
        switch_to_website:'切换为网站',
        apk_address:'请正确输入apk下载地址或Ipfs-CID',
        enter_package_name:'正确输入androidApp的包名',
        submit_modifications:'提交修改',
        back:'返回',
        title:'标题',
        submit_modification_proposal:'提交修改提案',
        create_dissemination:'创建传播型分享',
        establish_crowdfunding:'众筹成立自治组织: ',
        note:'注，该操作需额外支付“1个币”永久固定组织的账户上。',
        add_crowdfunding:'追加众筹到自治组织: ',
        purpose_crowdfunding:'本次众筹目的: ',
        organization_id:'组织ID（自选）:',
        soft_cap:'软顶(最低）: ',
        hard_cap:'硬顶（最大）: ',
        deadline_block_height:'截至区块高度（时间）：',
        select_time:'选择时间（高度自动换算）',
        destruction_ratio:'销毁比例:',
        my_first_investment:'我的投资（第一笔）: ',
        rent_nodes:'租用节点: ',
        adopt_zero_knowledge:'采用零知识认明',
        convert_current_ownership:'转换当前所有权',
        text_is:'is',
        current_page_id:'本页ID',
        create_promotion_crowdfunding:'创建 推广众筹',
        establish_organization_first:'出错！，需要先成立自治组织: ',
        your_account:'你的账户: ',
        members:'成员数: ',
        create_promotion_steps:'创建推广任务，需要三步骤：',
        generate_account:'1. 需要先部署隐私推广合约，获取到合约自动生成账户',
        create_task:'2. 创建任务并打款（当前界面）',
        vote_start_task:'3. 投票并启动任务',
        privacy_contract:'隐私合约',
        deploy_contract:'部署合约获取账户',
        privacy_contract:'隐私合约推广账户',
        privacy_contract_collection_account:'隐私合约收账账户',
        description_task:'本次任务说明',
        description:'说明: ',
        organization_investment:'组织的投入',
        my_investment:'我的投入',
        available:'可用',
        Wallet_plugin_user_selection:'钱包插件用户选择',
        current_selection:'当前选择',
        hint:'提示',
        confirm:'确定',
        cancel:'取消',
        submit:'提交',
        code_dissemination_required:'传播代码必填',
        tags_categories_required:'传播标签/分类必填',
        explanation_rights_required:'传播种子用户权利说明必填',
        explanation_obligations_required:'传播种子用户义务说明必填',
        cannot_signature:'不能以个人签名直接调用',
        not_owner:'你不是所有者！',
        operation_successful:'操作成功',
        operation_failed:'操作失败',
        unknown_error:'未知错误！',
        dissemination_required:'传播描述必填',
        dissemination_subject_required:'传播主题必填',
        asset_id_already_occupied:'资产ID已经被占用',
        activities_ongoing:'存在进行中的众筹',
        deadline_earlier_than_current:'截至时间(区块高度）小于当前时间',
        insufficient_account_balance:'账户余额不足！',
        system_error:'系统错误',
        cannot_find_root:'找不到‘根’自治组织',
    }
  }
}
