# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import paddle_pb2 as paddle__pb2

class TrainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainAndPredict = channel.unary_unary(
                '/paddle.TrainService/TrainAndPredict',
                request_serializer=paddle__pb2.Empty.SerializeToString,
                response_deserializer=paddle__pb2.TrainResult.FromString,
                )


class TrainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainAndPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainAndPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainAndPredict,
                    request_deserializer=paddle__pb2.Empty.FromString,
                    response_serializer=paddle__pb2.TrainResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddle.TrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainAndPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/paddle.TrainService/TrainAndPredict',
            paddle__pb2.Empty.SerializeToString,
            paddle__pb2.TrainResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
