// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: paddle.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paddle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_paddle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_paddle_proto_rawDescGZIP(), []int{0}
}

type TrainResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message        string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TrueLabel      int32  `protobuf:"varint,2,opt,name=true_label,json=trueLabel,proto3" json:"true_label,omitempty"`
	PredictedLabel int32  `protobuf:"varint,3,opt,name=predicted_label,json=predictedLabel,proto3" json:"predicted_label,omitempty"`
	ImageData      []byte `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *TrainResult) Reset() {
	*x = TrainResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paddle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResult) ProtoMessage() {}

func (x *TrainResult) ProtoReflect() protoreflect.Message {
	mi := &file_paddle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResult.ProtoReflect.Descriptor instead.
func (*TrainResult) Descriptor() ([]byte, []int) {
	return file_paddle_proto_rawDescGZIP(), []int{1}
}

func (x *TrainResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrainResult) GetTrueLabel() int32 {
	if x != nil {
		return x.TrueLabel
	}
	return 0
}

func (x *TrainResult) GetPredictedLabel() int32 {
	if x != nil {
		return x.PredictedLabel
	}
	return 0
}

func (x *TrainResult) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

var File_paddle_proto protoreflect.FileDescriptor

var file_paddle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x8e, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x75,
	0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x72, 0x75, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x32, 0x45, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x61, 0x64, 0x64, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_paddle_proto_rawDescOnce sync.Once
	file_paddle_proto_rawDescData = file_paddle_proto_rawDesc
)

func file_paddle_proto_rawDescGZIP() []byte {
	file_paddle_proto_rawDescOnce.Do(func() {
		file_paddle_proto_rawDescData = protoimpl.X.CompressGZIP(file_paddle_proto_rawDescData)
	})
	return file_paddle_proto_rawDescData
}

var file_paddle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paddle_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: paddle.Empty
	(*TrainResult)(nil), // 1: paddle.TrainResult
}
var file_paddle_proto_depIdxs = []int32{
	0, // 0: paddle.TrainService.TrainAndPredict:input_type -> paddle.Empty
	1, // 1: paddle.TrainService.TrainAndPredict:output_type -> paddle.TrainResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paddle_proto_init() }
func file_paddle_proto_init() {
	if File_paddle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paddle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paddle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paddle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paddle_proto_goTypes,
		DependencyIndexes: file_paddle_proto_depIdxs,
		MessageInfos:      file_paddle_proto_msgTypes,
	}.Build()
	File_paddle_proto = out.File
	file_paddle_proto_rawDesc = nil
	file_paddle_proto_goTypes = nil
	file_paddle_proto_depIdxs = nil
}
