/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRevealAttackVerifier,
  IRevealAttackVerifierInterface,
} from "../IRevealAttackVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[3]",
        name: "input",
        type: "uint256[3]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "r",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRevealAttackVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IRevealAttackVerifierInterface {
    return new Interface(_abi) as IRevealAttackVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRevealAttackVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRevealAttackVerifier;
  }
}
