"""update description for sites

Revision ID: e11f6ccb87c6
Revises: a11f4dfde53b
Create Date: 2023-06-21 18:58:33.103819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e11f6ccb87c6'
down_revision = 'e32f6ccb87c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'description', type_=sa.Text(), nullable=True)
   
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_for_lumi', sa.Boolean(),server_default=sa.text('false'), nullable=True))
   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
