// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: rpc/proto/files.proto

package filespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilesSrvClient is the client API for FilesSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesSrvClient interface {
	//  rpc Upload(stream Chunk) returns (UploadStatus) {}
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
}

type filesSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesSrvClient(cc grpc.ClientConnInterface) FilesSrvClient {
	return &filesSrvClient{cc}
}

func (c *filesSrvClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	out := new(AddResp)
	err := c.cc.Invoke(ctx, "/filespb.FilesSrv/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesSrvClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := c.cc.Invoke(ctx, "/filespb.FilesSrv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesSrvServer is the server API for FilesSrv service.
// All implementations must embed UnimplementedFilesSrvServer
// for forward compatibility
type FilesSrvServer interface {
	//  rpc Upload(stream Chunk) returns (UploadStatus) {}
	Add(context.Context, *AddReq) (*AddResp, error)
	Get(context.Context, *GetReq) (*GetResp, error)
	mustEmbedUnimplementedFilesSrvServer()
}

// UnimplementedFilesSrvServer must be embedded to have forward compatible implementations.
type UnimplementedFilesSrvServer struct {
}

func (UnimplementedFilesSrvServer) Add(context.Context, *AddReq) (*AddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedFilesSrvServer) Get(context.Context, *GetReq) (*GetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFilesSrvServer) mustEmbedUnimplementedFilesSrvServer() {}

// UnsafeFilesSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesSrvServer will
// result in compilation errors.
type UnsafeFilesSrvServer interface {
	mustEmbedUnimplementedFilesSrvServer()
}

func RegisterFilesSrvServer(s grpc.ServiceRegistrar, srv FilesSrvServer) {
	s.RegisterService(&FilesSrv_ServiceDesc, srv)
}

func _FilesSrv_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesSrvServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filespb.FilesSrv/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesSrvServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesSrv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesSrvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filespb.FilesSrv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesSrvServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesSrv_ServiceDesc is the grpc.ServiceDesc for FilesSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filespb.FilesSrv",
	HandlerType: (*FilesSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _FilesSrv_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FilesSrv_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proto/files.proto",
}
